server:
  port: 8848

spring:
  profiles:
    active: dev
  application:
    name: jetlinks-platform
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    default-property-inclusion: non_null
  resources:
    static-locations: file:./static/,/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/, classpath:/public/
  redis:
    host: 127.0.0.1
    port: 6279
    password: jetlinks
    lettuce:
      pool:
        max-active: 1024
    timeout: 20s
    serializer: jsk # 设置fst时,redis key使用string序列化,value使用 fst序列化.
  #    database: 3
  #        max-wait: 10s
  #=================数据库连接配置=============================
  datasource:
    #数据库地址
    url: jdbc:mysql://127.0.0.1:3308/jetlinks?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
    #数据库用户名
    username: root
    #数据库密码
    password: jetlinks
    #数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #最大连接数
      max-active: 20
      #最小空闲数
      min-idle: 8
      #初始化连接数
      initial-size: 10
      #对池中空闲的连接是否进行验证，验证失败则回收此连接
      test-while-idle: true
      #数据库心跳检测语句
      validation-query: SELECT 1
  reactor:
    debug-agent:
      enabled: false
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
          max-in-memory-size: 100MB
          socket-timeout: 5000
          connection-timeout: 8000
easyorm:
  default-schema: jetlinks # 数据库默认的schema
  dialect: mysql #数据库方言
  auto-ddl: true #关闭自动生成数据库表
elasticsearch:
  embedded:
    enabled: true # 为true时使用内嵌的elasticsearch,不建议在生产环境中使用
    data-path: ./data/elasticsearch
    port: 9200
    host: 0.0.0.0
  index:
    default-strategy: time-by-month #默认es的索引按月进行分表, direct则为直接操作索引.
    settings:
      number-of-shards: 1 # es 分片数量
      number-of-replicas: 0 # 副本数量
device:
  message:
    writer:
      time-series:
        enabled: true #写出设备消息数据到elasticsearch
captcha:
  enabled: false # 开启验证码
  ttl: 2m #验证码过期时间,2分钟
hsweb:
  cors:
    enable: true
    configs:
      - path: /**
        allowed-headers: "*"
        allowed-methods: [ "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS" ]
        allowed-origins: [ "*" ]
        allow-credentials: true
        max-age: 1800
  dict:
    enum-packages: org.jetlinks
  file:
    upload:
      static-file-path: ./static/upload
      static-location: /jetlinks/file/display
      storage: local
    minio:
      server:
        endpoint: http://127.0.0.1:8888
        access: admin
        secret: jetlinks
  webflux:
    response-wrapper:
      enabled: true #开启响应包装器(将返回值包装为ResponseMessage)
      excludes: # 这下包下的接口不包装
        - org.springdoc
  #  auth:   #默认的用户配置
  #    users:
  #      admin:
  #        username: admin
  #        password: admin
  #        name: 超级管理员
  authorize:
    auto-parse: true
  permission:
    filter:
      enabled: true # 设置为true开启权限过滤,赋权时,不能赋予比自己多的权限.
      exclude-username: admin # admin用户不受上述限制
      un-auth-strategy: ignore # error表示:发生越权时,抛出403错误. ignore表示会忽略越权的赋权.
  cache:
    type: redis
    redis:
      local-cache-type: guava
jetlinks:
  server-id: ${spring.application.name}:${server.port} #设备服务网关服务ID,不同服务请设置不同的ID
  logging:
    system:
      context:
        server: ${spring.application.name}
  protocol:
    spi:
      enabled: true # 为true时开启自动加载通过依赖引入的协议包
logging:
  level:
    org.jetlinks: debug
    rule.engine: debug
    org.hswebframework: debug
    org.springframework.transaction: debug
    org.springframework.data.r2dbc.connectionfactory: warn
    io.micrometer: warn
    org.hswebframework.expands: error
    system: debug
    org.jetlinks.rule.engine: warn
    org.jetlinks.supports.event: warn
    org.springframework: warn
    org.jetlinks.community.device.message.writer: warn
    org.jetlinks.community.timeseries.micrometer: warn
    org.jetlinks.community.elastic.search.service: trace
    org.jetlinks.community.elastic.search.service.reactive: trace
    org.jetlinks.community.network: warn
    io.vertx.mqtt.impl: warn
    #    org.springframework.data.elasticsearch.client: trace
    #    org.elasticsearch: error
    org.jetlinks.community.influx: trace
    org.elasticsearch: error
    org.elasticsearch.deprecation.search.aggregations.bucket.histogram: error
  config: classpath:logback-spring.xml
vertx:
  max-event-loop-execute-time-unit: seconds
  max-event-loop-execute-time: 30
  max-worker-execute-time-unit: seconds
  max-worker-execute-time: 30
  prefer-native-transport: true
micrometer:
  time-series:
    tags:
      server: ${spring.application.name}
    metrics:
      default:
        step: 30s
management:
  health:
    elasticsearch:
      enabled: false  # 关闭elasticsearch健康检查
springdoc:
  swagger-ui:
    path: /doc.html
  #  packages-to-scan: org.jetlinks
  group-configs:
    - group: 设备管理相关接口
      packages-to-scan:
        - org.jetlinks.community.device
      paths-to-exclude:
        - /device-instance/**
        - /device-product/**
        - /protocol/**
    - group: 规则引擎相关接口
      packages-to-scan: org.jetlinks.community.rule.engine.web
      paths-to-exclude: /api/**
    - group: 通知管理相关接口
      packages-to-scan: org.jetlinks.community.notify.manager.web
    - group: 设备接入相关接口
      packages-to-scan:
        - org.jetlinks.community.network.manager.web
        - org.jetlinks.community.device.web
      paths-to-match:
        - /gateway/**
        - /network/**
        - /protocol/**
    - group: 系统管理相关接口
      packages-to-scan:
        - org.jetlinks.community.auth
        - org.hswebframework.web.system.authorization.defaults.webflux
        - org.hswebframework.web.file
        - org.hswebframework.web.authorization.basic.web
        - org.jetlinks.community.logging.controller
  cache:
    disabled: false